### ISSUE TITLE
Differing fstab optimisations between guides

### ISSUE THREAD

**Issue by kjkent** [wmutschl/mutschler.dev#1]
Hi there,

Firstly, I want to say that after being recommended your guides, I'm really grateful for what an incredible resource they are. Thank you for creating and maintaining them.

I noticed in your two recently updated guides on Fedora Workstation:

1.  https://mutschler.dev/linux/fedora-btrfs-35/
2. https://mutschler.dev/linux/fedora-post-install/

There are slightly different recommendations regarding SSD/NVME optimisations in /etc/fstab, namely the extra addition of `noatime`, `space_cache`, and `commit=120` in the latter.

Which would you say represents your most current thoughts on these options?

**Comment by wmutschl** [comment]
Hi, in my most recent guides for Pop and elementary os I commented on this and I tend to stay closest to the default choices by the Fedora team. That is:

- compress=zstd:1: I use level 1 as this is recommended by the [Fedora team on a workstation](https://fedoraproject.org/wiki/Changes/BtrfsTransparentCompression#Simple_Analysis_of_btrfs_zstd_compression_level)
- space_cache=v2, which is also the [default in Fedora](https://pagure.io/fedora-btrfs/project/issue/24)
- discard=async: this will become the standard soon, see e.g. [enable discard=async by default](https://pagure.io/fedora-btrfs/project/issue/6)

Now there is some debate whether one should use [noatime (instead of the default relatime)](https://pagure.io/fedora-btrfs/project/issue/9), but personally I have not seen any difference, so I’m not using noatime in this guide.

So in Fedora, you really only have to add discard=async.

**Comment by kjkent** [comment]
Thank you for the clarification, Willi -- have a great weekend.
